-- ---------------------------------------------------------------------------
-- 033 — one explicitly authorized Ireland signup, without opening Ireland
--       (W9I-H.0)
--
-- THE PROBLEM
-- W9I-H needs its first Irish pilot tenant created through the NORMAL signup
-- path, so the pilot exercises the same flow a future customer will. But that
-- path refuses IE with 503 while IRELAND_ONBOARDING_ENABLED is off, and turning
-- that flag on opens Ireland to the public during a live regulatory filing.
--
-- This authorizes ONE signup attempt to pass the country-availability gate, and
-- nothing else. It is not regulatory authorization, not permission to file, not
-- permission to buy a +353, not permission to start a trial, and not a public
-- launch. Those remain separate gates and none of them consult this table.
--
-- WHY A TABLE, AND NOT SOMETHING THAT ALREADY EXISTS
-- Two candidates were examined against Stage C's required properties -- explicit
-- operator creation, single use, revocable before use, auditable, expiring,
-- unable to authorize any other key, unreachable from public APIs:
--
--   * oauth_states has exactly the right SHAPE (an opaque nonce, an expiry,
--     single-use semantics) and cannot be used: its tenant_id is
--     `not null references tenants(id)`, and a pilot grant exists precisely
--     BEFORE a tenant does. It also consumes by DELETING the row, which is
--     correct for a CSRF nonce and destroys the audit trail wanted here.
--
--   * system_meta is an untyped key/value bag with no expiry column, no
--     consumption column, and no way for the database to enforce single use --
--     the fence would be a compare-and-swap inside a JSON value, which PostgREST
--     cannot express safely.
--
-- An environment variable was rejected on the same grounds: it cannot be
-- consumed and cannot expire, which are two of the properties that make this
-- narrow rather than a permanent Ireland backdoor.
--
-- WHY THE ONBOARDING KEY IS THE RIGHT SCOPE
-- It is generated by the browser (crypto.randomUUID -- 122 bits of CSPRNG
-- entropy) BEFORE the availability gate is reached, validated server-side as a
-- strict uuid4, stable across retries for resume, and unique per signup attempt.
-- Authorizing (IE, that exact key) authorizes one signup and cannot be widened:
-- the key is the primary key here, so a grant can never speak for another.
--
-- CREATE AUTHORITY AND RESUME AUTHORITY ARE DIFFERENT THINGS
-- An earlier draft of this design said a consumed grant simply keeps satisfying
-- the gate, because 031's unique index on tenants.onboarding_key makes a second
-- tenant impossible. That proof holds only while the first tenant EXISTS.
--
-- Delete that tenant -- a legitimate purge, a GDPR erasure -- and the unique
-- index protects nothing: no row owns the key any more. A consumed grant that
-- still opened the gate would at that moment regain the power to create a brand
-- new tenant, turning an immutable audit record into durable authorization. That
-- is the hole this version closes.
--
-- So the two authorities are separated, and the separation lives in the gate:
--
--   UNUSED + unexpired          -> may create ONE tenant, then is consumed
--   CONSUMED + bound tenant     -> may RESUME that tenant, and nothing else
--     exists and id matches        (expiry is NOT re-checked -- see below)
--   CONSUMED + tenant gone      -> DENY. There is nothing to resume, and a
--                                  historical grant creates nothing.
--   CONSUMED + different tenant -> FAIL CLOSED. An integrity problem, never
--                                  repaired automatically.
--
-- EXPIRY MEANS "THIS INVITATION LAPSED", NOT "THIS ACCOUNT IS OVER". Before
-- consumption it decides whether a first tenant may be created. After
-- consumption it is not consulted: a customer part-way through onboarding must
-- not be bricked because a pilot invitation ran out behind them. Expiry never
-- restores create authority, because create authority requires consumed_at to be
-- NULL, and consumption is one-way.
-- ---------------------------------------------------------------------------

create table if not exists ireland_pilot_onboarding_grants (
    -- The exact uuid4 authorized. PRIMARY KEY, so one row can authorize exactly
    -- one signup attempt and a grant can never be widened to another key.
    onboarding_key text primary key,

    -- Constrained to IE, not to "some regulated country". Stage C forbids a
    -- generic country bypass, and the strongest way to say that is to make the
    -- database refuse one. Adding a country later is a deliberate migration
    -- somebody has to write, not a value somebody can type.
    iso_country text not null,

    created_at timestamptz not null default now(),

    -- NO DEFAULT, deliberately. Stage E says not to invent a grace period, and
    -- a default TTL here would be exactly that -- invented, then inherited by
    -- every future grant. The operator states when their authorization ends.
    expires_at timestamptz not null,

    -- Recorded, never deleted. Deleting on consumption is what oauth_states does
    -- and is right for a CSRF nonce; here the whole point is that an operator
    -- can later answer "who authorized this, and was it used?".
    consumed_at        timestamptz null,
    consumed_tenant_id uuid        null,

    -- Free text: which business, which conversation, which ticket. Operator
    -- provenance in the only form this deployment can honestly record.
    note text null,

    constraint ipog_country_chk check (iso_country = 'IE'),
    constraint ipog_key_is_uuid_chk check (
        onboarding_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
    constraint ipog_expiry_chk check (expires_at > created_at),
    constraint ipog_consumed_order_chk check (
        consumed_at is null or consumed_at >= created_at),
    -- STRUCTURAL ONLY, and named so it cannot be mistaken for more: it says the
    -- two consumption columns agree with each other -- an id cannot be recorded
    -- without the consumption that produced it. It does NOT prove the referenced
    -- tenant exists, now or ever. There is no foreign key here (see below), so
    -- nothing in this schema guarantees that row is still there, and any code
    -- using a consumed grant MUST look the tenant up rather than assume it.
    constraint ipog_consumed_columns_agree_chk check (
        consumed_tenant_id is null or consumed_at is not null)
);

-- consumed_tenant_id is deliberately NOT a foreign key, and the cost of that is
-- stated rather than glossed. A real FK would drag this table into tenant
-- deletion -- either blocking a GDPR erasure, or, with ON DELETE SET NULL,
-- quietly rewriting an audit record when a tenant is purged. W9E measured
-- exactly that class of problem on the regulatory event ledger.
--
-- WHAT IS GIVEN UP: this column is an IMMUTABLE HISTORICAL IDENTIFIER, not a
-- live referential guarantee. The tenant it names may have been deleted. No
-- CHECK in this table can tell you otherwise, and none pretends to. Every use
-- of a consumed grant must resolve the tenant and verify it, which is why the
-- gate algorithm below does exactly that.

comment on table ireland_pilot_onboarding_grants is
    'W9I-H.0: one operator-authorized Ireland signup attempt, scoped to a single '
    'onboarding_key. Passes the country-availability gate and NOTHING else -- not '
    'regulatory authorization, not provider filing, not number purchase, not '
    'billing, not public launch. Written only by an operator; no customer-facing '
    'API creates rows here.';

comment on column ireland_pilot_onboarding_grants.expires_at is
    'Operator-supplied, no default. An unconsumed grant past this is refused and '
    'the customer sees the ordinary country-unavailable response.';

comment on column ireland_pilot_onboarding_grants.consumed_at is
    'Set by a fenced UPDATE once the signup produced a durable tenant. A consumed '
    'grant still satisfies the gate for its own key so retries resume; a second '
    'tenant remains impossible via 031''s unique index on tenants.onboarding_key.';

-- RLS ON, NO POLICIES. The same shape migrations 027-030 use for every
-- regulatory table: denied outright to anon and authenticated, reachable only by
-- service_role, which bypasses RLS. A customer cannot read whether a grant
-- exists, which is what keeps the closed-country response indistinguishable.
alter table ireland_pilot_onboarding_grants enable row level security;

-- NO INDEX beyond the primary key. Every access is an exact lookup by
-- onboarding_key, which the PK already serves, and this table will hold a
-- handful of rows. An expiry sweep, if one is ever wanted, can add its own index
-- with the query that justifies it.

-- BACKFILL: none. A new table starts empty, and an empty table means Ireland is
-- closed to everyone -- which is the correct state until an operator says
-- otherwise about one specific key.

-- ---------------------------------------------------------------------------
-- Operator procedure. Deliberately plain SQL rather than an admin endpoint: this
-- deployment's admin surface is a single shared static key that cannot identify
-- individual operators, so an endpoint would add attack surface without adding
-- accountability. The Supabase SQL editor is already how migrations are applied
-- and already logs who ran what.
--
--   insert into ireland_pilot_onboarding_grants
--       (onboarding_key, iso_country, expires_at, note)
--   values ('<the customer's exact onboarding_key>', 'IE',
--           now() + interval '7 days', 'Ireland pilot — <business>, <ticket>');
--
-- To revoke before use:
--   delete from ireland_pilot_onboarding_grants
--    where onboarding_key = '<key>' and consumed_at is null;
--
-- Rollback:
--   drop table if exists ireland_pilot_onboarding_grants;
-- ---------------------------------------------------------------------------
